CREATE TABLE IF NOT EXISTS HELLO (
    ID VARCHAR NOT NULL
    , MESSAGE VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PROFILE (
    EMPLOYEE_ID VARCHAR(6) PRIMARY KEY
    , PROFILE_IMAGE_FILENAME VARCHAR(50) DEFAULT NULL
    , LAST_NAME VARCHAR(20) NOT NULL
    , FIRST_NAME VARCHAR(20) NOT NULL
    , YEARLY VARCHAR(2) DEFAULT NULL
    , SEX VARCHAR(1) NOT NULL
    , BLOOD_TYPE VARCHAR(1) DEFAULT NULL
    , TEAM VARCHAR(30) DEFAULT NULL
    , CUSTOMER VARCHAR(30) DEFAULT NULL
    , PROJECT VARCHAR(30) DEFAULT NULL
    , PRIVATE_SENTENCE VARCHAR(300) DEFAULT NULL
    , COMMENT VARCHAR(200) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS CAREER (
    EMPLOYEE_ID VARCHAR(6)
    , CAREER_ID VARCHAR(2)
    , YEAR VARCHAR(4) NOT NULL
    , MONTH VARCHAR(2) NOT NULL
    , EVENT VARCHAR(50) NOT NULL
    , PRIMARY KEY (EMPLOYEE_ID, CAREER_ID)
);
