CREATE TABLE IF NOT EXISTS ACCOUNT (
    EMPLOYEE_ID VARCHAR(6) PRIMARY KEY
    , PASSWORD TEXT NOT NULL
    , IS_ADMIN CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFILE (
    EMPLOYEE_ID VARCHAR(6) REFERENCES ACCOUNT
    , PICTURE BYTEA DEFAULT NULL
    , NAME VARCHAR(20) NOT NULL
    , HIRE_DATE DATE DEFAULT NULL
    , IS_NEWCOMER CHAR(1) NOT NULL
    , GENDER_ID CHAR(1) REFERENCES GENDER(GENDER_ID) DEFAULT NULL
    , BLOOD_TYPE_ID CHAR(1) REFERENCES BLOOD_TYPE(BLOOD_TYPE_ID) DEFAULT NULL
    , SALES_POINT VARCHAR(100) DEFAULT NULL
    , HOBBY VARCHAR(20) DEFAULT NULL
    , BIRTHPLACE CHAR(2) DEFAULT NULL --データモデル上出身地だが、出身テーブルの都道県IDと結びつかないといけないのでは
    , PRESENTATION BYTEA DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS CAREER (
    EMPLOYEE_ID VARCHAR(6) REFERENCES ACCOUNT
    , START_DATE DATE NOT NULL
    , END_DATE DATE DEFAULT NULL
    , PROJECT VARCHAR(20) NOT NULL
    , PROJECT_CONTENT VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS REGISTRATION_UPDATE (
    EMPLOYEE_ID VARCHAR(6) REFERENCES PROFILE(EMPLOYEE_ID)
    , UPDATE_DATE DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAM (
    TEAM_ID VARCHAR(3) PRIMARY KEY
    , TEAM_NAME VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS BELONG (
    EMPLOYEE_ID VARCHAR(10) PRIMARY KEY
    , TEAM_ID VARCHAR(3) REFERENCES TEAM(TEAM_ID) NOT NULL
);

CREATE TABLE IF NOT EXISTS BIRTHPLACE (
    CITY_ID VARCHAR(3) PRIMARY KEY
    , CITY VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS GENDER (
    GENDER_ID VARCHAR(3) PRIMARY KEY
    , GENDER VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS BLOOD_TYPE (
    BLOOD_TYPE_ID VARCHAR(3) PRIMARY KEY
    , BLOOD_TYPE VARCHAR(3)
);
