CREATE TABLE IF NOT EXISTS ACCOUNT (
    EMPLOYEE_ID VARCHAR(6) PRIMARY KEY
    , PASSWORD TEXT NOT NULL
    , IS_ADMIN CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFILE (
    EMPLOYEE_ID VARCHAR(6) REFERENCES ACCOUNT
    , PICTURE BYTEA DEFAULT NULL
    , NAME VARCHAR(20) NOT NULL
    , HIRE_DATE DATE DEFAULT NULL
    , IS_NEWCOMER CHAR(1) NOT NULL
    , GENDER_ID CHAR(1) DEFAULT NULL
    , BLOOD_TYPE_ID CHAR(1) DEFAULT NULL
    , SALES_POINT VARCHAR(100) DEFAULT NULL
    , HOBBY VARCHAR(20) DEFAULT NULL
    , BIRTHPLACE CHAR(2) DEFAULT NULL --データモデル上出身地だが、出身テーブルの都道県IDと結びつかないといけないのでは
    , PRESENTATION BYTEA DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS CAREER (
    EMPLOYEE_ID VARCHAR(6) REFERENCES ACCOUNT
    , START_DATE DATE NOT NULL
    , END_DATE DATE DEFAULT NULL
    , PROJECT VARCHAR(20) NOT NULL
    , PROJECT_CONTENT VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS REGISTRATION_UPDATE (
    EMPLOYEE_ID VARCHAR(6) REFERENCES PROFILE(EMPLOYEE_ID)
    , UPDATE_DATE DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
  USERNAME VARCHAR(255) NOT NULL
  , PASSWORD VARCHAR(60) NOT NULL
  , PRIMARY KEY (USERNAME)
);

CREATE TABLE IF NOT EXISTS USER_ROLE (
  USERNAME VARCHAR(255) NOT NULL
  , ROLE     VARCHAR(255) NOT NULL
  , PRIMARY KEY (USERNAME, ROLE)
);
